### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by autogyro** [foamliu/Image-Captioning-v2#1]
Hi, 
 没有看到这个文件夹和文件呢。

**Comment by Jordan-5i** [comment]
好像是没用，我试了一下，$ python train.py ，他会在当前目录下生成 BEST_checkpoint_.pth.tar，checkpoint_.pth.tar这两个文件，前者是训练时保留的最好的模型，然后$ python demo.py，demo.py中把图片放在images/文件夹下，图片名为image_0.jpg,........,image_i.jpg

**Comment by Jordan-5i** [comment]
> Hi,
> 没有看到这个文件夹和文件呢。

不知道现在恢回复对你有帮助吗？好像是没有的，我试了一下，$ python train.py ，他会在当前目录下生成 BEST_checkpoint_.pth.tar，checkpoint_.pth.tar这两个文件，前者是训练时保留的最好的模型，然后$ python demo.py，demo.py中把图片放在images/文件夹下，图片名为image_0.jpg,........,image_i.jpg

**Comment by autogyro** [comment]
谢谢你，Jordan-5i，呵呵。

**Comment by foamliu** [comment]
Nice, thank you guys.
