### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by HIHIHAHEI** [foamliu/Image-Captioning-v2#11]
运行train.py 由于pycharm下载resnet太慢就自行下载，但是后面程序运行时出错

File "E:/Users/pythoncx/workspace/Image-Captioning-PyTorch-master/train.py", line 141, in train
    for i, (imgs, caps, caplens) in enumerate(train_loader):
ValueError: too many values to unpack (expected 3)

**Comment by yNaiWen** [comment]
我在括号里随意添加了一个参数，类似于for i, (imgs, caps, caplens,nosense) in enumerate(train_loader):
问题便被解决了。

**Comment by foamliu** [comment]
try debug
