### ISSUE TITLE
image caption，结果中，出现多个同类型的词

### ISSUE THREAD

**Issue by cylvzj** [foamliu/Image-Captioning-v2#12]
你好，我用的是COCO数据集， 
两层LSTM模型， 一层用于实现自上而下的注意力，一层实现语言模型。

用jieba提取词
我将所有图片描述中，出现频率大于3次的词作为字典文件，一共有14226个词。
words = [w for w in word_freq.keys() if word_freq[w] > 3]

训练好模型后，在使用时，结果中出现多个同类型的词，比如：
放在 床上 的 笔记 笔记本 笔记本电脑 电脑
一个 小女 小女孩 女孩 站 在 一起

请教一下，应该怎样解决这个问题？

**Comment by foamliu** [comment]
Please take a look at the code and paper.
