### ISSUE TITLE
预训练模型已损坏

### ISSUE THREAD

**Issue by yNaiWen** [foamliu/Image-Captioning-v2#14]
作者你好，我注意到根据你的链接所下载的预训练模型应该已经损坏了，请问有可以用的模型吗？

**Comment by Lr-2002** [comment]
你好，我也遇到了同样的问题，请问你的问题解决了吗？

**Comment by yNaiWen** [comment]
解决了   自己训练一个就可以  数据集过大我只训练了其中一小部分

**Comment by Lr-2002** [comment]
能麻烦您把模型发到2629651228@qq.com 吗？（ 谢谢您了

**Comment by yNaiWen** [comment]
不行哦  我已经删掉了   你可以自己训练一个  想办法把数据集中json文件内容的一部分导出来成一个新的json文件  这样子可以降低内存需求和训练时间

**Comment by Lr-2002** [comment]
好的，谢谢
