### ISSUE TITLE
作者你好，能不能提供一下你提供的模型所对应的wordmap呢？没有这个文件的话那个模型貌似无法正常使用

### ISSUE THREAD

**Issue by HuhaAiay** [foamliu/Image-Captioning-v2#22]

**Comment by huangwenwenlili** [comment]
我通过pre_process.py产生的wordmap.json 长度为9534。但是训练的权重和模型中是9527，您能把您训练是的wordmap.json发到huangwenwenlili@126.com邮箱吗？谢谢。

**Comment by wjy3326** [comment]
请问你现在有那个wordmap.json吗？能发我邮箱吗1079158605@qq.com ？谢谢！

**Comment by huangwenwenlili** [comment]
没有，自己使用AI. Challenger生成了一个，但是长度比作者的长，解码出来是错误的。
Foamliu 您能提供一下wordmap.json吗？


谢谢。






 原始邮件 
发件人: wjy3326<notifications@github.com>
收件人: foamliu/Image-Captioning-PyTorch<Image-Captioning-PyTorch@noreply.github.com>
抄送: huangwenwenlili<huangwenwenlili@126.com>; Comment<comment@noreply.github.com>
发送时间: 2020年12月25日(周五) 18:29
主题: Re: [foamliu/Image-Captioning-PyTorch] 作者你好，能不能提供一下你提供的模型所对应的wordmap呢？没有这个文件的话那个模型貌似无法正常使用 (#22)


请问你现在有那个wordmap.json吗？能发我邮箱吗1079158605@qq.com ？谢谢！

**Comment by foamliu** [comment]
I don't have the environment any longer.

**Comment by wjy3326** [comment]
请问你现在使用的image caption模型是哪个啊？这个我还是跑不通，有bug。你跑的那个效果怎么样呢？
