### ISSUE TITLE
Does the WORDMAP in pre_process.py is produced by caption_train_annotations_20170902.json?

### ISSUE THREAD

**Issue by xiaofengWang-CCNU** [foamliu/Image-Captioning-v2#23]
Does the WORDMAP in pre_process.py is produced by caption_train_annotations_20170902.json?

Why i run the demo.py have a bad result?

Can you provide the WORDMAP?

Thank you

**Comment by YannBai** [comment]
> Does the WORDMAP in pre_process.py is produced by caption_train_annotations_20170902.json?
> 
> Why i run the demo.py have a bad result?
> 
> Can you provide the WORDMAP?
> 
> Thank you

Did you solve this problem? The wordmap count seem not correct~

**Comment by foamliu** [comment]
Uploaded WORDMAP.json
