### ISSUE TITLE
AttributeError: Can't get attribute '_rebuild_parameter' on <module 'torch._utils'

### ISSUE THREAD

**Issue by zhouzheng1123** [foamliu/Image-Captioning-v2#24]
when i run" python demo.py " that i want to see the demo result,there is a error like the title. and i searched this error in baidu.com,someone said that the version of pytorch  did not match the version of model.but my pytorch's version is the same as readme which is 0.4. so i want to konw if the pre-trained model was trained by other version of pytorch. or how to solve this error? please help me.thank you!

**Comment by foamliu** [comment]
WORDMAP.json
