### ISSUE TITLE
decoder.embedding(k_prev_words) index out of range in self

### ISSUE THREAD

**Issue by hw-liang** [foamliu/Image-Captioning-v2#26]
I followed you pipeline and create WORDMAP.json, but met problem when running demo.py.

when running 'embeddings = decoder.embedding(k_prev_words).squeeze(1)'. 
It reports error: IndexError: index out of range in self

**Comment by jsvwhxj** [comment]
do you solve this problem?
i have it too

**Comment by hw-liang** [comment]
I notice the issue is because the wordmap generated by pre_process.py has different (more) number of tokens from that used in pretrained model. If it's possible, can the author make public the wordmap used for checkpoint?

**Comment by jsvwhxj** [comment]
i put a train image in demo.py, it also print the same error

**Comment by foamliu** [comment]
Uploaded WORDMAP.json
