### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by HIHIHAHEI** [foamliu/Image-Captioning-v2#6]

**Comment by foamliu** [comment]
可以的 RMB100


在 2019-11-27 10:48:52，"HIHIHAHEI" <notifications@github.com> 写道：


你好，请问你可以把数据集发给我吗？现在官网无法下载数据集，网上也找不到。我想用这个数据集试试您的方法做实验！

**Comment by foamliu** [comment]
Feel free to drop an email to my email inbox.
