### ISSUE TITLE
Could not find data/WORDMAP.json 

### ISSUE THREAD

**Issue by joyce9533** [foamliu/Image-Captioning-v2#9]
I've downloaded the AI challenger dataset and put it into data folder, but I can't find WORDMAP.json when I run the demo.py.  
Thank you so much!

**Comment by HIHIHAHEI** [comment]
解码用的时resnet网络结构吗

**Comment by yujialeimustudent** [comment]
@foamliu 你好，能否提供一下单词表的json文件，我想测试一下。

**Comment by yNaiWen** [comment]
> @foamliu 你好，能否提供一下单词表的json文件，我想测试一下。

跑pre_process会自动生成json文件

**Comment by foamliu** [comment]
Thanks @yNaiWen . It is right.
